site:
  name: Samuel Grayson’s site
author: !include sam.yaml
blog:
  tagline: Thoughts on software, law, and history. I hope you find this blog as interesting as I do.
  content:
  - !include_body: illixr.md
# TODO[1]: blog page
# TODO[2]: front page: blog highlights, publications, projects, contact me, linktree

# TODO[2]: Decide on a logo.
# Books: https://publicdomainvectors.org/en/free-clipart/Home-library/84338.html
# Letter: Capital lambda, lowercase gamma
# Open source icon (Bootstrap icons, Google Fonts icons, Font Awesome, Flaticon?) (book, paper, glasses)
# Mathematical figure: Trefoil, mandelbrot

# https://fontawesome.com/v5.15/icons/comments?style=solid
# https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asubject%3A
# https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Ahive%3A
# https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Awaves%3A
# https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aclear_all%3A
# https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Anotes%3A
# https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Alibrary_books%3A

# TODO[3]: Family tree

# Implementation:
# https://medium.com/swlh/are-you-using-svg-favicons-yet-a-guide-for-modern-browsers-836a6aace3df
# https://lookout.dev/rules/use-svg-favicon
